### ISSUE TITLE
DASH video download bug

### ISSUE THREAD

**Issue by ObaidGH** [AlexxEG/YouTube-Downloader#1]
cannot download single dash video. gets deleted after completion

**Comment by ObaidGH** [comment]
Solved!!! DASH video download bug
just changed libvo_aacenc codec to libmp3lame in FFmpegHelper class

**Comment by AlexxEG** [comment]
Can you give me an example link I can use for testing this? All the videos I've seen so far is one video and one audio file.

**Comment by ObaidGH** [comment]
public const string CombineDash = " -report -y -i \"{0}\" -i \"{1}\" -vcodec copy -acodec libvo_aacenc \"{2}\"";

changed to : public const string CombineDash = " -report -y -i \"{0}\" -i \"{1}\" -vcodec copy -acodec libmp3lame \"{2}\"";

**Comment by ObaidGH** [comment]
public const string CombineDash = " -report -y -i \"{0}\" -i \"{1}\" -vcodec copy -acodec libvo_aacenc \"{2}\"";

changed to : public const string CombineDash = " -report -y -i \"{0}\" -i \"{1}\" -vcodec copy -acodec libmp3lame \"{2}\"";

just changed the audio codec -acodec libvo_aacenc to -acodec libmp3lame

**Comment by AlexxEG** [comment]
Oh, I meant a link to a video with only one DASH file, preferably the video you had problems with before fixing it. 

Just like to test it for myself too.

**Comment by ObaidGH** [comment]
i have no problem with any specific link
just the audio codec used in to combine DASH video wasn't working. so i changed it to libmp3lame
then it worked!!

**Comment by AlexxEG** [comment]
I think I'll add an option for choosing audio codec. Thank you for letting me know.

**Comment by ObaidGH** [comment]
one thing more i want to suggest.

**Comment by AlexxEG** [comment]
Sure, go ahead.

**Comment by ObaidGH** [comment]
an option can be added to download certain number of segments to download a time

**Comment by AlexxEG** [comment]
To clarify, download multiple parts of the same file and combining them at the end?

**Comment by ObaidGH** [comment]
Oh no you didn't get it
I mean can there be an option to download a certain number of queues at a time

**Comment by AlexxEG** [comment]
Ah, I understand now. Yeah, I'll add that. I'm out working for a few days but I'll try to work on it.
