### ISSUE TITLE
Error stopping playlist

### ISSUE THREAD

**Issue by ObaidGH** [AlexxEG/YouTube-Downloader#13]
![screenshot 2](https://cloud.githubusercontent.com/assets/14979775/19154691/39610606-8bf9-11e6-9895-7cd87a0cac32.png)

above is the screenshot when i try to stop downloading playlist...

**Comment by AlexxEG** [comment]
I think I've already fixed this in 68baf1117b1b39502b9464769f490871ee91685f.

Just didn't upload it until now.

**Comment by AlexxEG** [comment]
Can you confirm?

**Comment by ObaidGH** [comment]
it works fine now after updating.
