### ISSUE TITLE
Sign-in video login bug

### ISSUE THREAD

**Issue by ObaidGH** [AlexxEG/YouTube-Downloader#14]
`YTDAuthentication` username and password accepts null or empty

**Comment by ObaidGH** [comment]
But the LoginWindow closes after OK btn is clicked.

**Comment by AlexxEG** [comment]
It doesn't for me. It only closes when username and password fields is not empty.

Maybe you're thinking about Two Factor? That is optional, so it can be empty.

**Comment by ObaidGH** [comment]
It throws the error properly for me but the loginwindow exits

**Comment by AlexxEG** [comment]
Does it throw this error:
`throw new Exception($"{this.GetType().Name}: {nameof(username)} and {nameof(password)} can't be empty or null.");`

Or the red line of text above the buttons?

**Comment by ObaidGH** [comment]
the exception windows appears but when i click continue button the loginwindow disappears

**Comment by AlexxEG** [comment]
Hmm, an exception window shouldn't appear. What does it say?

This is what it should look like when you try to click OK with empty fields:
![image](https://cloud.githubusercontent.com/assets/803291/19193856/0bdf772c-8cac-11e6-8361-5a7d464b94ed.png)

**Comment by ObaidGH** [comment]
No this windows appears
![screenshot 4](https://cloud.githubusercontent.com/assets/14979775/19194023/ef68394e-8cc9-11e6-853c-9bb33ee4760b.png)

but when hit continue the login windows disappears

**Comment by AlexxEG** [comment]
Can you check if your local LoginDialog.cs file is up to date?

It should have a `private void btnOK_Click(object sender, EventArgs e)` which does a null check. You shouldn't be seeing that window.

**Comment by AlexxEG** [comment]
It should have this part: 
![image](https://cloud.githubusercontent.com/assets/803291/19194184/2b5f5558-8cad-11e6-992e-d27f1ff8182a.png)

**Comment by ObaidGH** [comment]
yup its there!

**Comment by ObaidGH** [comment]
but i have problem here

`if (videoInfo.RequiresAuthentication)
            {
                var auth = Dialogs.LoginDialog.Show(this);

```
            if (auth != null)
            {
                _auth = auth;
                btnGetVideo_Click(bwGetVideo, EventArgs.Empty);
                return;
            }
        }
        else if (videoInfo.Failure)
        {
            MessageBox.Show(this, "Couldn't retrieve video. Reason:\n\n" + videoInfo.FailureReason);
        }`
```

the login windows does not appear but when i make it this way the login windows appears

`if (videoInfo.RequiresAuthentication||videoInfo.Failure)
            {
                var auth = Dialogs.LoginDialog.Show(this);

```
            if (auth != null)
            {
                _auth = auth;
                btnGetVideo_Click(bwGetVideo, EventArgs.Empty);
                return;
            }
        }
        else if (videoInfo.Failure)
        {
            MessageBox.Show(this, "Couldn't retrieve video. Reason:\n\n" + videoInfo.FailureReason);
        }`
```

**Comment by AlexxEG** [comment]
Hmm, this makes no sense.

Can you also check if you have this line in your local `LoginDialog.Designer.cs`
`Line 97: this.btnOK.Click += new System.EventHandler(this.btnOK_Click);`

to make sure the event handler is actually being used.

**Comment by ObaidGH** [comment]
yes i have it

**Comment by AlexxEG** [comment]
I don't know why you're getting an error then. The exception gets thrown here, since it's given empty username/password:

![image](https://cloud.githubusercontent.com/assets/803291/19194662/af6fdae2-8cae-11e6-87a8-ca4e4d16aa8a.png)

But there is a null check in `btnOK_Click` here:

![image](https://cloud.githubusercontent.com/assets/803291/19194699/cd1cddf6-8cae-11e6-8aaa-2c06d9df72da.png)

So that error should never get thrown. This has to be something on your side I believe.

**Comment by ObaidGH** [comment]
i get this window with this text `YouTube said: This video contains content from` contained in it

so i changed the error filter in `YoutubeDlHelper.cs` class

after this the login window appears but still i get this
![screenshot 4](https://cloud.githubusercontent.com/assets/14979775/19196098/cbb93324-8cd1-11e6-8140-7dda16d03c11.png)

**Comment by ObaidGH** [comment]
the blocked video requires sign-in to confirm age

**Comment by ObaidGH** [comment]
yes i solved the whole thing :+1: 

just changed btnOK.DialogResult to None by default

**Comment by AlexxEG** [comment]
Good 👍

**Comment by AlexxEG** [comment]
I added a check for age gated content, so login should prompt for that also now. I didn't notice it since the error just says it's blocked, nothing about being age gated.

**Comment by ObaidGH** [comment]
are you working on the feature max no. of queues to download at a time?

**Comment by AlexxEG** [comment]
Yeah I am. I have a branch on my computer where I'm working on it. It just takes a while since I have to rework quite a lot of stuff.

**Comment by ObaidGH** [comment]
hmmmm. :+1:
