### ISSUE TITLE
Delete part downloaded video

### ISSUE THREAD

**Issue by ObaidGH** [AlexxEG/YouTube-Downloader#15]
Need to delete part downloaded single video when stoped.

**Comment by ObaidGH** [comment]
How do I check for file existence while downloading playlist

**Comment by AlexxEG** [comment]
What do you mean?

**Comment by ObaidGH** [comment]
i mean checking for video if already exists in the download directory for the playlist

**Comment by AlexxEG** [comment]
Ah, currently the program just overwrites without asking the user.

I'm thinking about appending a number instead, so if there already is a file with the same name the new file will be named "File (1)" for example.

**Comment by ObaidGH** [comment]
what i suggest is, if video already exists it should not be list in playlist listview

**Comment by AlexxEG** [comment]
Oh I understand now. That is a good idea. I'll implement that.

**Comment by ObaidGH** [comment]
I think i found the solution for this

**Comment by AlexxEG** [comment]
?

**Comment by ObaidGH** [comment]
right now i am too busy, i will let u know tommorrow

**Comment by ObaidGH** [comment]
this is my approach under _backgroundWorkerPlaylist_RunWorkerCompleted
`bool result = (bool)e.Result;

```
            _playlistCancel = false;
            btnGetPlaylist.Text = "Get";
            btnPlaylistDownloadAll.Enabled = result;
            btnPlaylistDownloadSelected.Enabled = result;
            lvPlaylistVideos.UseWaitCursor = false;

                foreach (string file in Directory.GetFiles(cbPlaylistSaveTo.Text))
                {
                    FileInfo f = new FileInfo(Path.GetFileNameWithoutExtension(file));
                    foreach (ListViewItem item in lvPlaylistVideos.Items)
                    {
                        FileInfo ff = new FileInfo(Path.GetFileNameWithoutExtension(item.Text));
                        if (f.Name == ff.Name)
                            lvPlaylistVideos.Items.Remove(item);
                    }
                }

            if (!result)
            {
                lvPlaylistVideos.Items.Clear();
            }`
```
