### ISSUE TITLE
Bug: Max download option not working with playlist

### ISSUE THREAD

**Issue by ObaidGH** [AlexxEG/YouTube-Downloader#19]
Am stuck in here! :confused:

![screenshot 7](https://cloud.githubusercontent.com/assets/14979775/19303459/5fa4f458-9086-11e6-8d1b-039b20a986e6.png)

**Comment by AlexxEG** [comment]
I forgot to tell the DownloadQueueHandler to handle PlaylistOperations. Easy fix.
