### ISSUE TITLE
Download resume

### ISSUE THREAD

**Issue by ObaidGH** [AlexxEG/YouTube-Downloader#21]
Resuming download doesn't seem to be working for single video when the download is paused
It works fine for playlist

![screenshot 13](https://cloud.githubusercontent.com/assets/14979775/19376964/063865a0-9200-11e6-8abb-ce326cf0bf1b.png)

**Comment by AlexxEG** [comment]
Is it reproducible? Works correctly for me.

**Comment by ObaidGH** [comment]
@AlexxEG  can i review your code for this

**Comment by AlexxEG** [comment]
[THIS](https://github.com/AlexxEG/YouTube-Downloader/blob/f2906f797ef3445d6d8756c271850e85556121c7/YouTube%20Downloader%20DLL/Operations/DownloadOperation.cs#L116) is the method that determines if the menu item should be available

**Comment by ObaidGH** [comment]
Oh i misscoded this way `return downloader != null && downloader.CanResume && this.Status == OperationStatus.Working;`

it works fine now

**Comment by AlexxEG** [comment]
👍
