### ISSUE TITLE
Playlist: selected videos download bug

### ISSUE THREAD

**Issue by ObaidGH** [AlexxEG/YouTube-Downloader#25]

**Comment by AlexxEG** [comment]
Sorry, can you explain further? Don't really understand.

**Comment by ObaidGH** [comment]
Suppose I have 200 videos in a playlist, When I select top nearest playlist indexes from playlist listview, the download starts immediately, but When I select last furthermost playlist indexes from playlist list view, it takes very long time to get playlist info

**Comment by AlexxEG** [comment]
Ah, I gotcha.

The reason is actually because it's not working at all. It tries to get the wrong video (at least when I'm trying to get last video in a 700+ long playlist. It tries to get 53rd video for some reason)

I'm gonna work on this.

**Comment by ObaidGH** [comment]
Okz :+1:

**Comment by ObaidGH** [comment]
:+1:  :smile:

**Comment by ObaidGH** [comment]
:disappointed: started facing the problem again

**Comment by ObaidGH** [comment]
:disappointed: Now the problem is when I download playlist videos with larger duration, it gets stuck whether the playlist may or may not contain 200+ videos

**Comment by AlexxEG** [comment]
Damn... I'll look into it.

**Comment by ObaidGH** [comment]
It works fine now :sweat_smile:
