### ISSUE TITLE
Playlist selected video download

### ISSUE THREAD

**Issue by ObaidGH** [AlexxEG/YouTube-Downloader#33]
Stuck in here
![playlistsel](https://cloud.githubusercontent.com/assets/14979775/19804311/25e18cb6-9d2b-11e6-868f-6099e4d85447.PNG)

**Comment by AlexxEG** [comment]
Going to need more information. It works for me.

What options are you using? (quality etc...) And playlist link if possible.

**Comment by ObaidGH** [comment]
All checked!

**Comment by AlexxEG** [comment]
Everything works for me with all options checked. Can you clear `%localappdata%\YouTube Downloader\logs`, try again then send me the logs?

**Comment by ObaidGH** [comment]
The log ends with `ERROR: list index out of range`

**Comment by AlexxEG** [comment]
Can I have the playlist link, if it's not private? Will be much easier for me.

**Comment by ObaidGH** [comment]
https://www.youtube.com/playlist?list=PLzufeTFnhupzBi22rTZgQbnRMWVCrUEvP

**Comment by AlexxEG** [comment]
I'll check it out, thank you. Btw have you downloaded large playlists before? Does it work correctly? (other than this ofc)

I never really download huge playlists, only smaller ones.

**Comment by ObaidGH** [comment]
Yes, I tried downloading the same link it worked then

**Comment by AlexxEG** [comment]
Ok 👍 I'll work on this.

**Comment by AlexxEG** [comment]
Found the issue. youtube-dl doesn't count duplicates, but mine does. So my program finds 295 videos, youtube-dl finds 294.

**Comment by ObaidGH** [comment]
Tried updating youtube-dl, but it's giving me the same problem

**Comment by AlexxEG** [comment]
It's now been fixed. Wasn't a issue with youtube-dl :)

**Comment by ObaidGH** [comment]
:+1:  problem solved. Thanx @AlexxEG
