### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by ObaidGH** [AlexxEG/YouTube-Downloader#41]
Came up with a new design. This is just a demo. Need to insert 'Add' command in the file menu strip

![new_design](https://cloud.githubusercontent.com/assets/14979775/20638765/55bbd11e-b3d6-11e6-9115-b1d3929312db.PNG)

Download tab page can now be eliminated

**Comment by AlexxEG** [comment]
I prefer my design to be honest. I generally try to avoid dialogs as much as possible.

This might work as an option however.

**Comment by ObaidGH** [comment]
yup, that was just an optional idea
