### ISSUE TITLE
btnGetPlaylist_Click bug

### ISSUE THREAD

**Issue by ObaidGH** [AlexxEG/YouTube-Downloader#5]
found a minor bug in

`private void btnGetPlaylist_Click(object sender, EventArgs e)
        {
            if (btnGetPlaylist.Text == "Get Playlist")
            {`

instead of checking `btnGetPlaylist.Text == "Get Playlist`
it should be `btnGetPlaylist.Text == "Get`

because the btnGetPlaylist.Text property is set to "Get"

**Comment by AlexxEG** [comment]
I should use the Tag property instead, in case the text changes again.
