### ISSUE TITLE
lvQueue.Items Flickering

### ISSUE THREAD

**Issue by ObaidGH** [AlexxEG/YouTube-Downloader#9]
lvQueue items flicker while downloading...

**Comment by AlexxEG** [comment]
Can you try to enable double buffering for the list?

**Comment by ObaidGH** [comment]
oh i got it! 
works fine now.

**Comment by AlexxEG** [comment]
Cool, I will make this change to the repo also. Thanks for checking for me :)

**Comment by ObaidGH** [comment]
from this `public ListViewEx() { }` to this `public ListViewEx() { DoubleBuffered = true; }`
